### ISSUE TITLE
ImportError: cannot import name 'AsyncAzureOpenAI' from 'openai' 

### ISSUE THREAD

**Issue by wrc3** [nlmatics/llmsherpa#26]
This error was generated using your code example. 

Traceback (most recent call last):
  File "C:\Users\x\wc-chat-pdf-py-willis\layout-pdf-reader.py", line 2, in <module>
    from llama_index.readers.schema.base import Document
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\__init__.py", line 17, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\embeddings\__init__.py", line 7, in <module>
    from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\embeddings\azure_openai.py", line 3, in <module>
    from openai import AsyncAzureOpenAI, AzureOpenAI
ImportError: cannot import name 'AsyncAzureOpenAI' from 'openai' (C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\__init__.py)

**Comment by ansukla** [comment]
Hello,

This is not related to LayoutPDFParser. It looks like you are setup to access AzureOpenAI, not OpenAI directly. Please follow the instructions in LlamaIndex to use AzureOpenAI instead of OpenAI. See this page for more information: https://gpt-index.readthedocs.io/en/latest/examples/customization/llms/AzureOpenAI.html
