### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by chengyjonathan** [nlmatics/llmsherpa#64]
self.pdf_reader = readers.LayoutPDFReader(
            self.api_url, 
            )
document = self.pdf_reader.read_pdf(final_location)

returns 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 21, in read_document
  File "/Users/joncheng/opt/miniconda3/envs/owlbear/lib/python3.10/site-packages/llmsherpa/readers/file_reader.py", line 72, in read_pdf
    response_json = json.loads(parser_response.data.decode("utf-8"))
  File "/Users/joncheng/opt/miniconda3/envs/owlbear/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/joncheng/opt/miniconda3/envs/owlbear/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/joncheng/opt/miniconda3/envs/owlbear/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Looks like there's an issue with handling jsondecoding errors.

I just provided a local file path.

**Comment by dalmia** [comment]
Switching to the docker image in [this](https://github.com/nlmatics/nlm-ingestor/issues/72#issuecomment-2218239935) comment worked for me.
